# Generated by Django 5.1.3 on 2024-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='user',
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='favoritecurrency',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='USD', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritecurrency',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default='USD', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='favoritecurrency',
            name='from_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='favoritecurrency',
            name='to_currency',
            field=models.CharField(max_length=10),
        ),
    ]
