# Generated by Django 5.1.3 on 2024-12-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
