# Generated by Django 5.0.7 on 2024-12-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_alter_favoritecurrency_converted_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='converted_amount',
        ),
    ]
