# Generated by Django 5.0.7 on 2024-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_remove_currencyrate_from_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
    ]
