# Generated by Django 5.0.7 on 2024-12-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_alter_currencyrate_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='converted_amount',
        ),
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='to_currency',
        ),
        migrations.AddField(
            model_name='favoritecurrency',
            name='currency',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='converter.currency'),
            preserve_default=False,
        ),
    ]
