# Generated by Django 5.0.7 on 2024-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0011_remove_favoritecurrency_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrate',
            old_name='currency_code',
            new_name='from_currency',
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='to_currency',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
