# Generated by Django 5.0.7 on 2024-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0012_rename_currency_code_currencyrate_from_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='from_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='to_currency',
            field=models.CharField(max_length=3),
        ),
    ]
