# Generated by Django 5.0.7 on 2024-12-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0014_favoritecurrency_converted_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecurrency',
            name='converted_amount',
        ),
    ]
