# Generated by Django 5.0.7 on 2024-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0015_remove_favoritecurrency_converted_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('conversion_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='favoritecurrency',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
